import {
  sqliteTable,
  text,
  integer,
  index,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";
import { users } from "./auth.schema";

/**
 * Native push registrations, kept separate from `push_subscriptions`.
 *
 * A Web Push subscription is a push-service URL plus the P-256 ECDH public key
 * and auth secret the browser's `PushManager` generated, and the worker
 * encrypts each payload to that keypair. React Native has no ServiceWorker and
 * no `PushManager`, so a native client has no such keypair to offer — it has an
 * opaque `ExponentPushToken[…]` and nothing else. The two are different enough
 * that sharing a table would mean making `p256dh` and `auth` nullable, and
 * SQLite cannot drop a NOT NULL constraint in place: it needs a
 * create-copy-drop-rename of a live table that also has an index and a foreign
 * key. A separate additive table avoids rewriting a table that is working.
 *
 * `installationId` rather than the token is the identity of a device. Expo
 * rotates tokens — on reinstall, on restore to a new handset, occasionally on
 * its own — and keying on the token would accumulate a dead row per rotation,
 * every one of which still looks live until something tries to send to it.
 */
export const expoPushSubscriptions = sqliteTable(
  "expo_push_subscriptions",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    /**
     * Stable per-install identifier generated by the client. One row per
     * installation per user; re-registering with a new token updates this row
     * rather than adding another.
     */
    installationId: text("installation_id").notNull(),
    /** `ExponentPushToken[…]`. Opaque; never returned by any API. */
    token: text("token").notNull(),
    /** Bumped only when the token actually changes. */
    tokenVersion: integer("token_version").notNull().default(1),
    /** "ios" | "android" — for diagnosing platform-specific delivery. */
    platform: text("platform"),
    deviceName: text("device_name"),
    createdAt: integer("created_at").notNull(),
    updatedAt: integer("updated_at").notNull(),
    lastUsedAt: integer("last_used_at"),
  },
  (t) => [
    // One row per installation per user: a device registering again replaces
    // its own row instead of leaving the previous token behind to be pushed to.
    uniqueIndex("expo_push_user_installation_idx").on(
      t.userId,
      t.installationId,
    ),
    index("expo_push_user_idx").on(t.userId),
  ],
);
